version: '3.4'
#@see https://docs.docker.com/compose/compose-file/compose-file-v3/
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "20m"

services:
  mailhog:
    image: mailhog/mailhog
    container_name: example_app_mailhog
    restart: unless-stopped
    logging: *default-logging

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'test_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Rq2G3gNP4fSYx8aj'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'bNAGLJS9cFF5S8Yh'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./db/data:/var/lib/mysql
    logging: *default-logging

  nginx:
    build: ./docker/nginx/build
    image: nginx
    container_name: example_app_nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/config:/etc/nginx/conf.d:ro
      - ./app:/app
    logging: *default-logging

volumes:
  composer: