version: '3.4'
#@see https://docs.docker.com/compose/compose-file/compose-file-v3/
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "20m"

services:
  mailhog:
    image: mailhog/mailhog
    container_name: example_app_mailhog
    restart: unless-stopped
    logging: *default-logging

  db:
    image: mysql
    container_name: example_app_db
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./db/data:/var/lib/mysql
    logging: *default-logging

  nginx:
    build: ./docker/nginx/build
    image: nginx
    container_name: example_app_nginx
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/config:/etc/nginx/conf.d:ro
      - ./app:/app
    logging: *default-logging

volumes:
  composer:
