controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

dukecity_command_scheduler:
    resource: "@DukecityCommandSchedulerBundle/Resources/config/routing.php"
    prefix:   /